name: patch

on:
  pull_request:
    paths:
      - 'docker/patch/**'
      - '.github/workflows/patch_build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-debian-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-debian

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          context: .
          file: ./docker/patch/Dockerfile
          tags: timescaledev/timescale-analytics:nightly

      - name: Run Doc Tests
        run: |
          docker run -d --name toolkit_test -e POSTGRES_HOST_AUTH_METHOD=trust -p 5432:5432 timescaledev/timescale-analytics:nightly
          cargo run --manifest-path ./tools/sql-doctester/Cargo.toml -- -h localhost -s "CREATE EXTENSION timescaledb_toolkit; SET SESSION TIMEZONE TO 'UTC'" -p 5432 docs
      #TODO can/should we run our other tests also?

      - name: Push
        id: image_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./docker/patch/Dockerfile
          tags: timescaledev/timescale-analytics:nightly,timescaledev/timescaledb-toolkit:nightly

      - name: Image digest
        run: echo ${{ steps.image_build.outputs.digest }}
